---
title: "paricipation project"
author: "Karen Vieira"
date: "7/5/2020"
output: html_document
---

```{r}
library(tidyverse)
library(gapminder)
```

```{r}
# to find what path your on
getwd()

```

**CVS FILE**
```{r}
(gap_asia_2007 <- gapminder %>% filter(year == 2007, continent == "Asia"))


# to save a data set from console to computer
library(here)
write_csv(gap_asia_2007, here::here("data", "s008_data", "exported_file.csv"))

# how to find and show dataset on computer
read_csv(here::here("data", "s008_data", "exported_file.csv"))

# how to get a dataset off the internet
url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/magazines.csv"
read_csv(url)
```

**Excel**
```{r}

library(readxl) 

#how to create a new folder from within R
dir.create(here::here("data", "s008_data_2"), recursive = TRUE)

# to download a excel file you must first save that file to an object. Here we save it to an object we have called xls_url
xls_url <- "http://gattonweb.uky.edu/sheather/book/docs/datasets/GreatestGivers.xls"
# the next step is to use the download.file() function to download the file onto your computer
download.file(xls_url, here::here("data", "s008_data_2", "some_file.xls"), mode = "wb")


# Naming a file “some_file” is extremely bad practice (hard to keep track of the files), and you should always give it a more descriptive name. Often, it’s a good idea to name the file similarly (or the same as) the original file (sometimes that might not be a good idea if the original name is non-descriptive).

# There’s handy trick to extract the filename from the URL:
file_name <- basename(xls_url)
download.file(xls_url, here::here("data", "s008_data", file_name), mode = "wb")
# after running this the file name showsup in tht enviorment as an object

#to import an excel file into R
read_excel(here::here("data", "s008_data", file_name))
```

**SPSS**
```{r}

library(haven)

(clevel <- haven::read_spss(here::here("data", "s008_data", "clevel.sav")))

# we are doing the following to clean up the dataset
clevel_cleaned <-
  clevel %>% 
  mutate(language = as_factor(language),
         gender = as_factor(gender),
         isClevel = factor(isClevel, 
                           levels = c(0, 1), 
                           labels = c("No", "Yes"))
  ) %>% 
  print()

# then we go ahead and change the SPSS file into a CSV file
#we do this to 1) save space 2) make it easier to pull up later on
write_csv(clevel_cleaned, here::here("data", "s008_data", "clevel_cleaned.csv"))
```

**SAVING PLOTS**
```{r}

#here a plot is being created for us to use as an example 
clevel_plot <-
  clevel_cleaned %>% 
  mutate(isClevel = recode(isClevel, 
                           No = "Below C-level", 
                           Yes = "C-level"),
         gender = recode(gender,
                         Female = "Women",
                         Male = "Men")) %>% 
  ggplot(aes(paste(isClevel, gender, sep = "\n"), Extraversion, color = gender)) +
  geom_boxplot() +
  geom_jitter(height = .2) +
  scale_color_manual(values = c("#1b9e77", "#7570b3")) +
  ggtitle("Extraversion Stan Scores") +
  scale_y_continuous(breaks = 1:9)  %>% 
  print()

## NONE OF THESE WORK :)

dir.create(here::here("output"))
dir.create(here::here("output", "figures"))
ggsave(here::here("output", "figures", "clevel_extraversion.svg"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.eps"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.pdf"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.tiff"), clevel_plot)
ggsave(here::here("output", "figures", "clevel_extraversion.png"), clevel_plot)
```

```{r}

```


